### ISSUE TITLE
Event header styling

### ISSUE THREAD

**Issue by daniel-norman-sociomantic** [sociomantic-tsunami/bacalao#10]
- [ ] The event header need to be sized correctly
- [ ] The font colour of the address is blue
- [ ] The venue name is black and the font size is smaller
- [ ] There's a separator between the time and the venue/address

![screen shot 2015-04-07 at 12 10 55](https://cloud.githubusercontent.com/assets/2950127/7021341/be2b4b28-dd20-11e4-9ee9-21585d54e74f.png)

**Comment by leandro-lucarella-sociomantic** [comment]
Closing because the project will be archived.
