### ISSUE TITLE
Event info styling

### ISSUE THREAD

**Issue by daniel-norman-sociomantic** [sociomantic-tsunami/bacalao#11]
- [ ] Add 'Description' above the descrption. 
- [ ] The avatars go on the right hand side.
- [ ] The avatars are circular
- [ ] Ensure the avatars have a size so it's not determined by the image size.
- [ ] Write how many places are left.
- [ ] style the number of places left(blue slightly bigger, red if one left) I can take care of adding the css classes if needed.

The design shows empty circles for places available. Please ignore this for now. 
In the future we will hide some avatars if an event is attended by a large number of people.

![screen shot 2015-04-07 at 12 10 55](https://cloud.githubusercontent.com/assets/2950127/7021471/217b0d70-dd22-11e4-9d29-fbdf4d3ba445.png)

**Comment by leandro-lucarella-sociomantic** [comment]
Closing because the project will be archived.
