### ISSUE TITLE
New event form styling

### ISSUE THREAD

**Issue by daniel-norman-sociomantic** [sociomantic-tsunami/bacalao#12]
The missing date input and plus and minus buttons are in a different issue.

The button is to be titled 'Create and join'

Currently:
![screen shot 2015-04-07 at 12 41 02](https://cloud.githubusercontent.com/assets/2950127/7021580/6326a1a2-dd23-11e4-856c-cdc4d9d36317.png)

Wanted:

![screen shot 2015-04-07 at 12 40 41](https://cloud.githubusercontent.com/assets/2950127/7021577/575e4028-dd23-11e4-9cb7-7fd477f00c8c.png)

**Comment by leandro-lucarella-sociomantic** [comment]
Closing because the project will be archived.
