### ISSUE TITLE
Implement client side error handling

### ISSUE THREAD

**Issue by daniel-norman-sociomantic** [sociomantic-tsunami/bacalao#2]
If a request to the API failed(e.g. saving an event) the following should happen:
1. an failed request Action must be dispatched (important to contain `cid`(a unique client id) in the action payload)
2. The store will find the failed entity(most likely an event) with the help of the cid 
3. The store will set a new property e.g. `failedAPI` to true. 
4. A change event is triggered 
5. App state is updated
6. Re-render of that event with a try again button which will attempt to send again to the api

The problem with the suggested approach above is, the user doesn't know why the request failed.
Hence it may be useful to introduce a new `notifications` or `errors` store which will also listen to any action which should in turn notify the user. Accordingly, a `notifications` component could render all notifications which haven't been read(`read` property which could be saved in the store)

**Comment by leandro-lucarella-sociomantic** [comment]
Closing because the project will be archived.
