### ISSUE TITLE
Prune the venue name so it's not too long

### ISSUE THREAD

**Issue by daniel-norman-sociomantic** [sociomantic-tsunami/bacalao#9]
As in the example below:

The venue name needs to be pruned to ensure it fits inside the `.event-box__header` div

![screen shot 2015-04-07 at 12 10 55](https://cloud.githubusercontent.com/assets/2950127/7021207/ada218dc-dd1f-11e4-8569-8b9f45a1258c.png)

**Comment by leandro-lucarella-sociomantic** [comment]
Closing because the project will be archived.
